// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBidaOG9us4-l6ZDwJ8-pTwIKDo6O5BYyU',
    appId: '1:185449724504:web:011eb4267d16644cc6e82d',
    messagingSenderId: '185449724504',
    projectId: 'ayurvan-b2bf2',
    authDomain: 'ayurvan-b2bf2.firebaseapp.com',
    databaseURL: 'https://ayurvan-b2bf2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ayurvan-b2bf2.appspot.com',
    measurementId: 'G-TXJXJ9N8KP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfxePqJRyMDJNzX0Y9Bl9DFBzRUMGHVZU',
    appId: '1:185449724504:android:98928e0143fadaeec6e82d',
    messagingSenderId: '185449724504',
    projectId: 'ayurvan-b2bf2',
    databaseURL: 'https://ayurvan-b2bf2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ayurvan-b2bf2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3UOnrvRuNikww-vJ9MRkDbvIW_AbxgIo',
    appId: '1:185449724504:ios:1d8ab440b5dfba9cc6e82d',
    messagingSenderId: '185449724504',
    projectId: 'ayurvan-b2bf2',
    databaseURL: 'https://ayurvan-b2bf2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ayurvan-b2bf2.appspot.com',
    androidClientId: '185449724504-ng8e5a5bq0ut9402131uud0ft5kqt6t7.apps.googleusercontent.com',
    iosClientId: '185449724504-gdb7ic4qh52g99qdt5o2ebv6ggdegs9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.carouselAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3UOnrvRuNikww-vJ9MRkDbvIW_AbxgIo',
    appId: '1:185449724504:ios:1d8ab440b5dfba9cc6e82d',
    messagingSenderId: '185449724504',
    projectId: 'ayurvan-b2bf2',
    databaseURL: 'https://ayurvan-b2bf2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ayurvan-b2bf2.appspot.com',
    androidClientId: '185449724504-ng8e5a5bq0ut9402131uud0ft5kqt6t7.apps.googleusercontent.com',
    iosClientId: '185449724504-gdb7ic4qh52g99qdt5o2ebv6ggdegs9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.carouselAssignment',
  );
}
